import type { Metadata } from "next"
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import Navbar from "@/components/Navbar"
import { Footer } from "@/components/Footer"
import AuthWrapper from "@/components/AuthWrapper"
import "./globals.css"
import type React from "react"
import { Toaster } from "@/components/ui/toaster"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "HUKUM",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AuthWrapper>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </AuthWrapper>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}

